// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9uXW3B0TobeOxviZ6LycLHY9a6EtsRus',
    appId: '1:894468743368:web:6a232a0d49c78c8f6c85fd',
    messagingSenderId: '894468743368',
    projectId: 'akgec-286e2',
    authDomain: 'akgec-286e2.firebaseapp.com',
    storageBucket: 'akgec-286e2.appspot.com',
    measurementId: 'G-4W08DRHTD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9Tzkn749oJHiDnW9DZs0M1pgadZPfVk',
    appId: '1:894468743368:android:e48c1d4eeeae87226c85fd',
    messagingSenderId: '894468743368',
    projectId: 'akgec-286e2',
    storageBucket: 'akgec-286e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOnohFixJplVfyyIL1uxmurPXquqYJ3Xs',
    appId: '1:894468743368:ios:ea4fd47172e84f336c85fd',
    messagingSenderId: '894468743368',
    projectId: 'akgec-286e2',
    storageBucket: 'akgec-286e2.appspot.com',
    iosClientId: '894468743368-e92vv00cjk96k0tnrnblj1fniqf176tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOnohFixJplVfyyIL1uxmurPXquqYJ3Xs',
    appId: '1:894468743368:ios:ea4fd47172e84f336c85fd',
    messagingSenderId: '894468743368',
    projectId: 'akgec-286e2',
    storageBucket: 'akgec-286e2.appspot.com',
    iosClientId: '894468743368-e92vv00cjk96k0tnrnblj1fniqf176tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginProj',
  );
}
